matches:
  - trigger: ";test"
    replace: "Espanso is working!"
    
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"


  - trigger: ";gac"
    replace: "git add . && git commit -m \"$|$\""
    
  - trigger: ";jlog"
    form:
        console.log("[[name]]", [[name]]);

  - trigger: ";sel"
    replace: "SELECT * FROM $|$ WHERE 1=1 ORDER BY -id;"

  - trigger: ";todo"
    replace: "// TODO: $|$"

  - trigger: ";af"
    replace: "const $|$ = () => {\n\n};"

  - trigger: ";em"
    replace: "swapnilupadhyaykharel@gmail.com"
    force_clipboard: true
    clipboard_threshold: 0

  - trigger: ":lenny"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: 'cat ~/.config/espanso/lennys.txt | rofi -dmenu -p "Lenny" -i | awk -F "|" "{print \$3}" | sed "s/^[ \t]*//;s/[ \t]*$//"'